plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.1'
	id 'io.spring.dependency-management' version '1.1.6'
	id 'com.github.node-gradle.node' version '7.1.0'
}

group = 'de.dreja'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// SpringBoot
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.session:spring-session-core'

	// Persistence
	implementation 'org.liquibase:liquibase-core'
	// https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc
	implementation 'org.xerial:sqlite-jdbc:3.46.0.0'
	// https://mvnrepository.com/artifact/org.hibernate.orm/hibernate-community-dialects
	implementation 'org.hibernate.orm:hibernate-community-dialects:6.5.2.Final'
	// https://mvnrepository.com/artifact/org.hibernate.orm/hibernate-core
	implementation 'org.hibernate.orm:hibernate-core:6.5.2.Final'

	// Tests
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

node {
	version = '20.18.0'
	npmInstallCommand = 'install'
	distBaseUrl = 'https://nodejs.org/dist'
	download = true
}

tasks.register('cleanJavascript', Copy) {
	group = 'build'
	from layout.buildDirectory.dir('typescript/compiled')
	include '**/*.js'
	exclude '**/*.test.js'
	into layout.buildDirectory.dir('resources/main/static/js')
	filter {
		String line -> line.startsWith('export {};') ? null : line
	}
	filter {
		String line -> line.startsWith('import') ? null : line
	}
	filter {
		String line -> line.startsWith('export var') ? line.replaceFirst('export var', 'var') : line
	}
	filter {
		String line -> line.startsWith('export function') ? line.replaceFirst('export function', 'function') : line
	}
}

tasks.register('compileTypescript', NpxTask) {
	group = 'build'
	dependsOn tasks.named('npmInstall')
	command = 'tsc'
	inputs.files(project.fileTree('src/main/typescript').filter {
		File f -> f.name.endsWith('.ts')
	})
	outputs.dir(layout.buildDirectory.dir('typescript/compiled'))
	finalizedBy(tasks.named('cleanJavascript'))
}

tasks.register('testTypescript', NpxTask) {
	group = 'verification'
	dependsOn tasks.named('npmInstall')
	command = 'jest'
	inputs.files(project.fileTree('src/main/typescript').filter {
		File f -> f.name.endsWith('.ts')
	})
	outputs.dir(layout.buildDirectory.dir('test-results/typescript'))
}


tasks.named('compileJava') {
	dependsOn(tasks.named('compileTypescript'), tasks.named('cleanJavascript'))
}
tasks.named('processResources') {
	dependsOn(tasks.named('compileTypescript'), tasks.named('cleanJavascript'))
}
tasks.named('test') {
	dependsOn(tasks.named('testTypescript'))
}

javadoc {
	options.encoding = 'UTF-8'
}



tasks.named('test') {
	useJUnitPlatform()
}

tasks.named('bootJar') {
	archiveFileName = 'quiz-presenter.jar'
}
