spring:
    application:
        jpa:
            properties:
                hibernate:
                    dialect: org.hibernate.community.dialect.SQLiteDialect

de:
  dreja:
    quiz:
      game-modes:
        grosser-preis:
          starting-points: 100
          point-increment: 100
      datasource:
        driver-class-name: org.sqlite.JDBC