// This file is auto-generated by @hey-api/openapi-ts

export enum Color {
    RED = 'RED',
    BLUE = 'BLUE',
    GREEN = 'GREEN',
    YELLOW = 'YELLOW',
    ORANGE = 'ORANGE',
    PURPLE = 'PURPLE',
    TURQUOISE = 'TURQUOISE',
    WHITE = 'WHITE'
}

export enum Emoji {
    DUCK = 'DUCK',
    SHARK = 'SHARK',
    CAMEL = 'CAMEL',
    FLAMINGO = 'FLAMINGO',
    HEDGEHOG = 'HEDGEHOG',
    CAT = 'CAT',
    CRAB = 'CRAB',
    KANGAROO = 'KANGAROO',
    HIPPOPOTAMUS = 'HIPPOPOTAMUS',
    GORILLA = 'GORILLA',
    TIGER = 'TIGER',
    LEOPARD = 'LEOPARD',
    LAMA = 'LAMA',
    RHINOCEROS = 'RHINOCEROS',
    HORSE = 'HORSE',
    SLOTH = 'SLOTH',
    ELEFANT = 'ELEFANT',
    MOUSE = 'MOUSE',
    RABBIT = 'RABBIT',
    BEAVER = 'BEAVER',
    CROCODILE = 'CROCODILE',
    TORTOISE = 'TORTOISE',
    SNAKE = 'SNAKE',
    DOLPHIN = 'DOLPHIN',
    OTTER = 'OTTER',
    WHALE = 'WHALE',
    ROOSTER = 'ROOSTER',
    EAGLE = 'EAGLE',
    SWAN = 'SWAN',
    PARROT = 'PARROT',
    PENGUIN = 'PENGUIN',
    DOG = 'DOG'
}

export type GameDto = {
    state: GameState;
    sections: Array<GameSectionDto>;
    availableEmoji: Array<Emoji>;
    availableColors: Array<Color>;
    players: Array<Player>;
    teams: Array<Team>;
    roundCounter: number;
    currentSection?: string;
    currentRound?: string;
};

export type GameRoundDto = {
    key: string;
    state: RoundState;
    currentlyAttempting: Array<Color>;
    alreadyAttempted: Array<Color>;
    completedBy: Array<Color>;
    inSection: string;
};

export type GameSectionDto = {
    name: string;
    rounds: Array<GameRoundDto>;
};

export enum GameState {
    TEAM_SETUP = 'TEAM_SETUP',
    PLAYER_SETUP = 'PLAYER_SETUP',
    CONTROLLER_SETUP = 'CONTROLLER_SETUP',
    GAME_ACTIVE = 'GAME_ACTIVE'
}

export type Player = {
    emoji: Emoji;
    name: string;
    points: number;
    assignedToTeam?: Color;
};

export enum RoundState {
    WAIT_ON_REVEAL = 'WAIT_ON_REVEAL',
    SHOW_QUESTION = 'SHOW_QUESTION',
    BUZZER_ACTIVE = 'BUZZER_ACTIVE',
    TEAM_CAN_ATTEMPT = 'TEAM_CAN_ATTEMPT',
    COMPLETE_WITH_RESULTS = 'COMPLETE_WITH_RESULTS',
    CLOSED = 'CLOSED'
}

export type Team = {
    color: Color;
    points: number;
    players: Array<Emoji>;
    gamepadId?: string;
};

export type GetGameResponse = (GameDto);

export type GetGameError = unknown;

export type $OpenApiTs = {
    '/debug/game/': {
        get: {
            res: {
                /**
                 * OK
                 */
                '200': GameDto;
            };
        };
    };
};