// This file is auto-generated by @hey-api/openapi-ts

export type Color = 'RED' | 'BLUE' | 'GREEN' | 'YELLOW' | 'ORANGE' | 'PURPLE' | 'TURQUOISE' | 'WHITE';

export const Color = {
    RED: 'RED',
    BLUE: 'BLUE',
    GREEN: 'GREEN',
    YELLOW: 'YELLOW',
    ORANGE: 'ORANGE',
    PURPLE: 'PURPLE',
    TURQUOISE: 'TURQUOISE',
    WHITE: 'WHITE'
} as const;

export type Emoji = 'DUCK' | 'SHARK' | 'CAMEL' | 'FLAMINGO' | 'HEDGEHOG' | 'CAT' | 'CRAB' | 'KANGAROO' | 'HIPPOPOTAMUS' | 'GORILLA' | 'TIGER' | 'LEOPARD' | 'LAMA' | 'RHINOCEROS' | 'HORSE' | 'SLOTH' | 'ELEFANT' | 'MOUSE' | 'RABBIT' | 'BEAVER' | 'CROCODILE' | 'TORTOISE' | 'SNAKE' | 'DOLPHIN' | 'OTTER' | 'WHALE' | 'ROOSTER' | 'EAGLE' | 'SWAN' | 'PARROT' | 'PENGUIN' | 'DOG';

export const Emoji = {
    DUCK: 'DUCK',
    SHARK: 'SHARK',
    CAMEL: 'CAMEL',
    FLAMINGO: 'FLAMINGO',
    HEDGEHOG: 'HEDGEHOG',
    CAT: 'CAT',
    CRAB: 'CRAB',
    KANGAROO: 'KANGAROO',
    HIPPOPOTAMUS: 'HIPPOPOTAMUS',
    GORILLA: 'GORILLA',
    TIGER: 'TIGER',
    LEOPARD: 'LEOPARD',
    LAMA: 'LAMA',
    RHINOCEROS: 'RHINOCEROS',
    HORSE: 'HORSE',
    SLOTH: 'SLOTH',
    ELEFANT: 'ELEFANT',
    MOUSE: 'MOUSE',
    RABBIT: 'RABBIT',
    BEAVER: 'BEAVER',
    CROCODILE: 'CROCODILE',
    TORTOISE: 'TORTOISE',
    SNAKE: 'SNAKE',
    DOLPHIN: 'DOLPHIN',
    OTTER: 'OTTER',
    WHALE: 'WHALE',
    ROOSTER: 'ROOSTER',
    EAGLE: 'EAGLE',
    SWAN: 'SWAN',
    PARROT: 'PARROT',
    PENGUIN: 'PENGUIN',
    DOG: 'DOG'
} as const;

export type GameDto = {
    state: GameState;
    sections: {
        [key: string]: GameSectionDto;
    };
    availableEmoji: Array<Emoji>;
    availableColors: Array<Color>;
    players: {
        [key: string]: Player;
    };
    teams: {
        [key: string]: Team;
    };
    roundCounter: number;
    currentSection?: string;
    currentRound?: string;
};

export type GameRoundDto = {
    key: string;
    state: RoundState;
    currentlyAttempting: Array<Color>;
    alreadyAttempted: Array<Color>;
    completedBy: Array<Color>;
    inSection: string;
};

export type GameSectionDto = {
    name: string;
    rounds: Array<GameRoundDto>;
};

export type GameState = 'TEAM_SETUP' | 'PLAYER_SETUP' | 'CONTROLLER_SETUP' | 'GAME_ACTIVE';

export const GameState = {
    TEAM_SETUP: 'TEAM_SETUP',
    PLAYER_SETUP: 'PLAYER_SETUP',
    CONTROLLER_SETUP: 'CONTROLLER_SETUP',
    GAME_ACTIVE: 'GAME_ACTIVE'
} as const;

export type Player = {
    emoji: Emoji;
    name: string;
    points: number;
    assignedToTeam?: Color;
};

export type RoundState = 'WAIT_ON_REVEAL' | 'SHOW_QUESTION' | 'BUZZER_ACTIVE' | 'TEAM_CAN_ATTEMPT' | 'COMPLETE_WITH_RESULTS' | 'CLOSED';

export const RoundState = {
    WAIT_ON_REVEAL: 'WAIT_ON_REVEAL',
    SHOW_QUESTION: 'SHOW_QUESTION',
    BUZZER_ACTIVE: 'BUZZER_ACTIVE',
    TEAM_CAN_ATTEMPT: 'TEAM_CAN_ATTEMPT',
    COMPLETE_WITH_RESULTS: 'COMPLETE_WITH_RESULTS',
    CLOSED: 'CLOSED'
} as const;

export type Team = {
    color: Color;
    points: number;
    players: Array<Emoji>;
    gamepadId?: string;
};

export type GetGameResponse = (GameDto);

export type GetGameError = unknown;

export type $OpenApiTs = {
    '/debug/game/': {
        get: {
            res: {
                /**
                 * OK
                 */
                '200': GameDto;
            };
        };
    };
};