// This file is auto-generated by @hey-api/openapi-ts

/**
 * Option of a multiple-choice question
 */
export type AnswerOption = {
    answerId: string;
    correct: boolean;
    optionType: string;
};

export enum Color {
    RED = 'RED',
    BLUE = 'BLUE',
    GREEN = 'GREEN',
    YELLOW = 'YELLOW',
    ORANGE = 'ORANGE',
    PURPLE = 'PURPLE',
    TURQUOISE = 'TURQUOISE',
    WHITE = 'WHITE'
}

export enum Emoji {
    DUCK = 'DUCK',
    SHARK = 'SHARK',
    CAMEL = 'CAMEL',
    FLAMINGO = 'FLAMINGO',
    HEDGEHOG = 'HEDGEHOG',
    CAT = 'CAT',
    CRAB = 'CRAB',
    KANGAROO = 'KANGAROO',
    HIPPOPOTAMUS = 'HIPPOPOTAMUS',
    GORILLA = 'GORILLA',
    TIGER = 'TIGER',
    LEOPARD = 'LEOPARD',
    LAMA = 'LAMA',
    RHINOCEROS = 'RHINOCEROS',
    HORSE = 'HORSE',
    SLOTH = 'SLOTH',
    ELEFANT = 'ELEFANT',
    MOUSE = 'MOUSE',
    RABBIT = 'RABBIT',
    BEAVER = 'BEAVER',
    CROCODILE = 'CROCODILE',
    TORTOISE = 'TORTOISE',
    SNAKE = 'SNAKE',
    DOLPHIN = 'DOLPHIN',
    OTTER = 'OTTER',
    WHALE = 'WHALE',
    ROOSTER = 'ROOSTER',
    EAGLE = 'EAGLE',
    SWAN = 'SWAN',
    PARROT = 'PARROT',
    PENGUIN = 'PENGUIN',
    DOG = 'DOG'
}

/**
 * Overall container for the entire game setup and state
 */
export type Game = {
    state: GameState;
    sections: Array<GameSection>;
    availableEmoji: Array<Emoji>;
    availableColors: Array<Color>;
    players: Array<Player>;
    teams: Array<Team>;
    roundCounter: number;
    currentSection?: string;
    currentRound?: string;
};

/**
 * One round (aka question) in the quiz
 */
export type GameRound = {
    key: string;
    state: RoundState;
    currentlyAttempting: Array<Color>;
    alreadyAttempted: Array<Color>;
    completedBy: Array<Color>;
    inSection: string;
    question: (TextMultipleChoiceQuestionDto);
};

/**
 * A named group of rounds within the game (e.g. Category)
 */
export type GameSection = {
    name: string;
    rounds: Array<GameRound>;
};

export enum GameState {
    TEAM_SETUP = 'TEAM_SETUP',
    PLAYER_SETUP = 'PLAYER_SETUP',
    CONTROLLER_SETUP = 'CONTROLLER_SETUP',
    GAME_ACTIVE = 'GAME_ACTIVE'
}

/**
 * One player within the game with a unique Emoji
 */
export type Player = {
    emoji: Emoji;
    name: string;
    points: number;
    assignedToTeam?: Color;
};

/**
 * Question or task asked of the players
 */
export type Question = {
    givenAnswers: Array<TeamAnswer>;
    questionType: string;
};

export enum RoundState {
    WAIT_ON_REVEAL = 'WAIT_ON_REVEAL',
    SHOW_QUESTION = 'SHOW_QUESTION',
    BUZZER_ACTIVE = 'BUZZER_ACTIVE',
    TEAM_CAN_ATTEMPT = 'TEAM_CAN_ATTEMPT',
    COMPLETE_WITH_RESULTS = 'COMPLETE_WITH_RESULTS',
    CLOSED = 'CLOSED'
}

/**
 * One team of players within the game with a unique color
 */
export type Team = {
    color: Color;
    points: number;
    players: Array<Emoji>;
    gamepadId?: string;
    gamepadRequested: boolean;
};

export type TeamAnswer = {
    byTeam: Color;
    answer: string;
};

export type TextAnswerOptionDto = AnswerOption & {
    answerText?: string;
} & {
    answerText: string;
};

export type TextMultipleChoiceQuestionDto = Question & {
    points?: number;
    questionText?: string;
    answerOptions?: Array<(TextAnswerOptionDto)>;
} & {
    points: number;
    questionText: string;
    answerOptions: Array<(TextAnswerOptionDto)>;
};

/**
 * Add a new player to the current game
 */
export type AddPlayerEventDto = GameEventDto & {
    playerName?: string;
} & {
    playerName: string;
};

/**
 * Adds a new, empty team to the game
 */
export type AddTeamEventDto = GameEventDto & {
    targetColor?: Color;
};

/**
 * Assigns the current controller ID to the team
 */
export type AssignGamepadEventDto = GameEventDto & {
    teamColor?: Color;
    gamepadId?: string;
} & {
    teamColor: Color;
};

export type GameEventDto = {
    type: string;
};

/**
 * Change the emoji of an existing player
 */
export type ReRollPlayerEmojiEventDto = GameEventDto & {
    currentEmoji?: Emoji;
} & {
    currentEmoji: Emoji;
};

/**
 * Remove a player from the current game
 */
export type RemovePlayerEventDto = GameEventDto & {
    playerEmoji?: Emoji;
} & {
    playerEmoji: Emoji;
};

/**
 * Remove a team from the current game
 */
export type RemoveTeamEventDto = GameEventDto & {
    teamColor?: Color;
} & {
    teamColor: Color;
};

/**
 * Rename a player
 */
export type RenamePlayerEventDto = GameEventDto & {
    playerEmoji?: Emoji;
    newName?: string;
} & {
    playerEmoji: Emoji;
    newName: string;
};

/**
 * Requests the assignment of a controller to the team
 */
export type RequestGamepadEventDto = GameEventDto & {
    teamColor?: Color;
} & {
    teamColor: Color;
};

/**
 * Shuffle all players into new teams
 */
export type ShuffleTeamsEventDto = GameEventDto & {
    newTeams?: Array<Color>;
} & {
    newTeams: Array<Color>;
};

export type GetGameResponse = (Game);

export type GetGameError = unknown;

export type GetEventResponse = ((AddPlayerEventDto | AddTeamEventDto | AssignGamepadEventDto | ReRollPlayerEmojiEventDto | RemovePlayerEventDto | RemoveTeamEventDto | RenamePlayerEventDto | RequestGamepadEventDto | ShuffleTeamsEventDto));

export type GetEventError = unknown;

export type $OpenApiTs = {
    '/debug/game/': {
        get: {
            res: {
                /**
                 * OK
                 */
                '200': Game;
            };
        };
    };
    '/debug/event/': {
        get: {
            res: {
                /**
                 * OK
                 */
                '200': (AddPlayerEventDto | AddTeamEventDto | AssignGamepadEventDto | ReRollPlayerEmojiEventDto | RemovePlayerEventDto | RemoveTeamEventDto | RenamePlayerEventDto | RequestGamepadEventDto | ShuffleTeamsEventDto);
            };
        };
    };
};